root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
plugins:
  - "@typescript-eslint"
parserOptions:
  sourceType: module
rules:
  "@typescript-eslint/member-delimiter-style": off
