name: automatic publish
on:
  push:
    tags:
      - "*"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: npm ci
        run: npm ci
      - name: release
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
